language: python

 #which versions of python to test against
python:
  - "2.7"
  - "3.3"
  
 # command to install dependencies
install:
  - pip install codecov
  - pip install coverage
  
script: 
  - python -m unittest # command to run unit test
  - coverage run test.py # command to run code coverage
#can do additional things, say send out reports, which we will discuss next time

after_success:
  - codecov -s